import { password, cancel, note, intro, outro, text } from "@clack/prompts";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { cleanMultiline } from "./cleanMultiline";
import crypto from "node:crypto";

export async function hatch(
    fromInit: boolean = false,
    folder: string = process.cwd(),
) {
    if (!fromInit) {
        await intro("nuit hatch");
    }

    const discordToken = await password({
        message: "Nuit instance's Discord token",
        mask: "•",
        clearOnError: true,
        validate: (value: string | undefined) => {
            if (!value) return "Enter a token";
            if (!/[\w-]{24,26}\.[\w-]{6}\.[\w-]{27,38}/.test(value)) {
                return "This is not a valid token.";
            }
            return;
        },
    });

    let discordClientId;

    try {
        const req = await fetch("https://discord.com/api/v10/users/@me", {
            method: "PATCH",
            headers: {
                Authorization: `Bot ${String(discordToken)}`,
            },
        });

        if (!req.ok) {
            throw new Error("InvalidToken");
        }

        const body = (await req.json()) as { id: string };
        discordClientId = body.id;
    } catch {
        return console.error(
            "Failed to get Discord client ID, maybe you put the wrong token?",
        );
    }

    const discordClientSecret = await password({
        message: "Nuit instance's Discord client secret",
        mask: "•",
        clearOnError: true,
        validate: (value: string | undefined) => {
            if (!value) return "Enter a client secret";
            if (!/^[\w\-]{32}$/.test(value)) {
                return "This is not a valid client secret.";
            }
            return;
        },
    });

    const postgresDatabaseUrl = await password({
        message: "Postgres Database URL",
        mask: "•",
        clearOnError: true,
        validate: (value: string | undefined) => {
            if (!value) return "Enter a database URL";
            if (!/^postgresql:\/\/[^:]+:[^@]+@[^:]+:\d+\/\w+$/.test(value)) {
                return "This is not a valid database URL.";
            }
            return;
        },
    });

    const sessionSecret = crypto.randomBytes(32).toHex();

    await note(
        `The base URL is where your bot is hosted and publicly accessible (e.g., https://nuit-bot.onrender.com)
        The URL that must be added in your Discord bot panel's Redirect URIs is {base url}/api/auth/callback/discord.`.trim(),
    );

    const callbackUrl = await text({
        message: "Base URL",
    });

    const dotEnv =
        `# Generated by "nuit hatch", do NOT edit this file outside of hatch.
    # Discord credentials
    DISCORD_TOKEN=${String(discordToken)}
    DISCORD_CLIENT_ID=${String(discordClientId)}
    DISCORD_CLIENT_SECRET=${String(discordClientSecret)}

    # Better Auth secrets
    BETTER_AUTH_URL=${String(callbackUrl)}
    BETTER_AUTH_SECRET=${sessionSecret}

    # Database credentials
    DATABASE_URL=${String(postgresDatabaseUrl)}`.trim();

    await writeFile(path.join(folder, ".env"), dotEnv, { encoding: "utf-8" });

    await outro(
        cleanMultiline(`Done hatching! Start your Nuit instance with
        ${fromInit == true ? `cd ${folder.replaceAll("\\", "/").split("/").pop()}` : ""}
        bun ci
        bun run dev --register
        
        # In another terminal
        bun run dev:web`),
    );
}
